### ISSUE TITLE
No longer works since API address changed by TfL

### ISSUE THREAD

**Issue by Pecnut** [jacobtomlinson/tube-status#5]
Since 1 September 2024, the `cloud.tfl.gov.uk` API addresses no longer work, and hence this package has stopped working.

I believe `https://api.tfl.gov.uk/line/mode/tube,overground,dlr,elizabeth-line,tram/status` might be a good replacement for the API address.

**Comment by jacobtomlinson** [comment]
The last commit to this repo was 10 years ago, I'm impressed that it still has users! I'm going to archive this repo (see #6) but if someone wants to fork and maintain it then please feel free.
